### PR TITLE
fix(index): npx log install result to stdout not in stderr

### PR DESCRIPTION
**Pull request by akaguny**
BREAKING CHANGE: some automatization may expect old behavior

# What / Why
> installed is success and will be write to stdout, not in stderr

## References
* similar to https://github.com/npm/cli/pull/79

### CODE REVIEW

**Comment by karfau** [comment]
I would vote against this change:
I believe writing to stdout should be preserved to the tool/package/module that is invoked.
So that the output of the tool (the thing the "npx user" actually cares about) can be piped into a different place.
If the data of the tool is e.g. JSON your change would add that line to the JSON output which leads to a syntax error when trying to read/parse it.

**Comment by ljharb** [comment]
I agree; diagnostic output doesn’t belong on stdout.

**Comment by akaguny** [comment]
anyone in cli team, can you comment?
If change is needed i will complete PR with test issues.
Else i will close PR with comment

**Comment by KilianKilmister** [comment]
@akaguny @ljharb 
General callout for people potentially interested in collaborating on an npx alternative in light of its unmaintained status.
[A project proposal can be found here.](https://github.com/ModernJavaScriptDevelopment/ModernJavaScriptDevelopment/issues/1)

**Comment by ljharb** [comment]
It’s still maintained, and an npx that doesn’t ship with npm is not useful.

**Comment by KilianKilmister** [comment]
> It’s still maintained, and an npx that doesn’t ship with npm is not useful.

Sure hasn't looked like it is maintained fo a few months now
and i don't see how not shipping with npm has much effect on usability. besides, npm is just another package and can be used as a dependency. and much of what it uses under the hood is awailable in seperate packages aswell, so i really can't agree on your second statement.

Anyways, i've already been intrusive enough. i don't want to take up any more space here for non-npx things

**Comment by darcyclarke** [comment]
@akaguny thanks for this submission - as @ljharb noted, this repo is going to eventually be archived & we'll be deprecating the package as `npx` comes with `npm` by default & the code now solely lives in https://github.com/npm/cli

**Pull request closed without merging**
