### PR TITLE
deps: update npm for node 14

### LINKED ISSUE #67: [BUG] All commands throw error: cb.apply is not a function
# What / Why
Using npx to run a command, for example `npx webpack`, throws: "cb.apply is not a function".
Here's the output log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/tin/.nvm/versions/node/v14.5.0/bin/node',
1 verbose cli   '/home/tin/.nvm/versions/node/v14.5.0/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'webpack@latest',
1 verbose cli   '--global',
1 verbose cli   '--prefix',
1 verbose cli   '/home/tin/.npm/_npx/42772',
1 verbose cli   '--loglevel',
1 verbose cli   'error',
1 verbose cli   '--json'
1 verbose cli ]
2 info using npm@5.1.0
3 info using node@v14.5.0
4 verbose npm-session 181369e9e33cec15
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/webpack 936ms
8 http fetch GET 200 https://registry.npmjs.org/webpack/-/webpack-4.43.0.tgz 278ms
9 silly pacote tag manifest for webpack@latest fetched in 1256ms
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at /home/tin/.nvm/versions/node/v14.5.0/lib/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
10 verbose stack     at FSReqCallback.oncomplete (fs.js:177:5)
11 verbose cwd /tmp
12 verbose Linux 5.4.0-40-generic
13 verbose argv "/home/tin/.nvm/versions/node/v14.5.0/bin/node" "/home/tin/.nvm/versions/node/v14.5.0/lib/node_modules/npx/node_modules/npm/bin/npm-cli.js" "install" "webpack@latest" "--global" "--prefix" "/home/tin/.npm/_npx/42772" "--loglevel" "error" "--json"
14 verbose node v14.5.0
15 verbose npm  v5.1.0
16 error cb.apply is not a function
17 verbose exit [ 1, true ]
```

## When
Tried `npx webpack` and `npx create-react-app`.

### Steps to Reproduce
Having `node:v14.5.0`, `npm:6.14.6` and `npx:10.2.2`.
Try any command.

### PR DESCRIPTION
**Pull request by dschaller**
Upgrades npm to the minimum supported version for node 14.

Currently npx error when run with node 14:
```bash
10 verbose stack TypeError: cb.apply is not a function
10 verbose stack     at /home/tin/.nvm/versions/node/v14.5.0/lib/node_modules/npx/node_modules/npm/node_modules/graceful-fs/polyfills.js:287:18
10 verbose stack     at FSReqCallback.oncomplete (fs.js:177:5)
```

This upgrade solves that issue.

This is also happening on node 12.8.3 which can be seen [here](https://github.com/lyft/clutch/runs/929002224)

## References
Fixes #67

### CODE REVIEW

**Comment by dschaller** [comment]
Any chance you can take a look @claudiahdz? (tagging you since you did the latest release)

**Comment by dschaller** [comment]
@zkat can you merge this?

**Comment by zkat** [comment]
@dschaller sorry, neither of the people you've pinged so far actually work on this anymore. Cc @MylesBorins

**Comment by ljharb** [comment]
npx’s code is now contained within the npm cli, so updating it here wouldn’t likely have any effect.

**Comment by MylesBorins** [comment]
@dschaller I surfaced this PR to the @npm/cli team. We might want to archive this repository as the npx source code is now contained within the CLI as mentioned by @ljharb

**Pull request closed without merging**
